a <- read.csv("CYED-H.csv",sep=",",check.names = F)
b <- read.csv("CYHU-H.csv",sep=",",check.names = F)
c <- read.csv("CYOW-H.csv",sep=",",check.names = F)
d <- read.csv("CYQG-H.csv",sep=",",check.names = F)
e <- read.csv("CYTZ-H.csv",sep=",",check.names = F)
f <- read.csv("CYVR-H.csv",sep=",",check.names = F)
g <- read.csv("CYWG-H.csv",sep=",",check.names = F)
h <- read.csv("CYYC-H.csv",sep=",",check.names = F)
j<- read.csv("KAGC-H.csv",sep=",",check.names = F)
k <- read.csv("KBJC-H.csv",sep=",",check.names = F)
l <- read.csv("KBNA-H.csv",sep=",",check.names = F)
m<- read.csv("KBOS-H.csv",sep=",",check.names = F)
n <- read.csv("KBUF-H.csv",sep=",",check.names = F)
o <- read.csv("KCPS-H.csv",sep=",",check.names = F)
p <- read.csv("KCQT-H.csv",sep=",",check.names = F)
q <- read.csv("KDAL-H.csv",sep=",",check.names = F)
r <- read.csv("KDCA-H.csv",sep=",",check.names = F)
s <- read.csv("KEWR-H.csv",sep=",",check.names = F)
t <- read.csv("KFRG-H.csv",sep=",",check.names = F)
u <- read.csv("KFUL-H.csv",sep=",",check.names = F)
v <- read.csv("KFXE-H.csv",sep=",",check.names = F)
w <- read.csv("KLUF-H.csv",sep=",",check.names = F)
x <- read.csv("KMDW-H.csv",sep=",",check.names = F)
y<- read.csv("KNYC-H.csv",sep=",",check.names = F)
z<- read.csv("KPHL-H.csv",sep=",",check.names = F)
aa<- read.csv("KRDU-H.csv",sep=",",check.names = F)
bb <- read.csv("KSJC-H.csv",sep=",",check.names = F)
cc <- read.csv("KSTP-H.csv",sep=",",check.names = F)
dd <- read.csv("KTPF-H.csv",sep=",",check.names = F)
ee <- read.csv("KVGT-H.csv",sep=",",check.names = F)

ff <- read.csv("CYED2019H.csv",sep=",",check.names = F)
gg <- read.csv("CYHU2019H.csv",sep=",",check.names = F)
hh <- read.csv("CYOW2019H.csv",sep=",",check.names = F)
ii <- read.csv("CYQG2019H.csv",sep=",",check.names = F)
jj <- read.csv("CYTZ2019H.csv",sep=",",check.names = F)
kk <- read.csv("CYVR2019H.csv",sep=",",check.names = F)
ll <- read.csv("CYWG2019H.csv",sep=",",check.names = F)
mm <- read.csv("CYYC2019H.csv",sep=",",check.names = F)
oo<- read.csv("KAGC2019H.csv",sep=",",check.names = F)
pp <- read.csv("KBJC2019H.csv",sep=",",check.names = F)
qq <- read.csv("KBNA2019H.csv",sep=",",check.names = F)
rr<- read.csv("KBOS2019H.csv",sep=",",check.names = F)
ss <- read.csv("KBUF2019H.csv",sep=",",check.names = F)
tt <- read.csv("KCPS2019H.csv",sep=",",check.names = F)
uu <- read.csv("KCQT2019H.csv",sep=",",check.names = F)
vv <- read.csv("KDAL2019H.csv",sep=",",check.names = F)
ww <- read.csv("KDCA2019H.csv",sep=",",check.names = F)
xx <- read.csv("KEWR2019H.csv",sep=",",check.names = F)
yy <- read.csv("KFRG2019H.csv",sep=",",check.names = F)
zz <- read.csv("KFUL2019H.csv",sep=",",check.names = F)
aaa <- read.csv("KFXE2019H.csv",sep=",",check.names = F)
bbb <- read.csv("KLUF2019H.csv",sep=",",check.names = F)
ccc <- read.csv("KMDW2019H.csv",sep=",",check.names = F)
ddd<- read.csv("KNYC2019H.csv",sep=",",check.names = F)
eee<- read.csv("KPHL2019H.csv",sep=",",check.names = F)
fff<- read.csv("KRDU2019H.csv",sep=",",check.names = F)
ggg <- read.csv("KSJC2019H.csv",sep=",",check.names = F)
hhh <- read.csv("KSTP2019H.csv",sep=",",check.names = F)
iii <- read.csv("KTPF2019H.csv",sep=",",check.names = F)
jjj <- read.csv("KVGT2019H.csv",sep=",",check.names = F)


combined <-rbind(a,b,c,d,e,f,g,h,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,bb,cc,dd,ee,ff,gg,hh,ii,jj,kk,ll,mm,oo,pp,qq,rr,ss,tt,uu,vv,ww,xx,yy,zz,aaa,bbb,ccc,ddd,eee,fff,ggg,hhh,iii,jjj)
NHL <-read.csv("NHLCombinedwith2018.csv",sep=",",check.names = F)


colnames(combined)
names(combined) <- c("Weather Station Code", "Data Type","Data Date","Time Zone","Latitude","Longitude","Elevation","Temperature","Feels Like","Dew Point","Relative Humidity","Wet Bulb Temp","Wind Direction","Wind Speed","Cloud Cover percent","Cloud Ceiling","Cloud Cover Type","Visibility","Solar Irradiance Beam","Solar Irradiance Diffuse","Solar Irradiance Global","Solar Irradiance Possible Beam","Solar Irradiance Possible Global","Solar Irradiance ET","Probability of Precipitation","Water EQ","Snowfall","Pressure Inches","Pressure Millibars","Weather Code Digit Numeric","Weather Code Alpha Numeric","Weather Text")

library(splitstackshape)
combined <-cSplit(combined, 'Data Date', sep=" ", type.convert=FALSE)

combined$Key2 <-paste(combined$`Weather Station Code`,combined$`Data Date_1`,combined$`Data Date_2`)
combined$Key2[1]

NHL$Key2 <- paste(NHL$`Weather Station`,NHL$Date3,"07")
NHL$Key2[1]

NHLCombined <-merge(NHL, combined, by="Key2")

write.csv(NHLCombined,file="NHLCombinedwith2018Hourly.csv")
